=== PhDxunq/JSON/Lesson3/Bai3/MonHoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListMonHoc">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="MonHoc" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MaMh" type="xs:string"/>
                        <xs:element name="TenMh" type="xs:string"/>
                        <xs:element name="SoGio">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="4"/>
                                    <xs:maxInclusive value="48"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== PhDxunq/JSON/Lesson3/Bai3/MonHoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="MonHoc.xsl" type="text/xsl"?>
<ListMonHoc 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="MonHoc.xsd">
    <MonHoc>
        <MaMh>CSDL</MaMh>
        <TenMh>Cơ sở dữ liệu</TenMh>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMh>MCB</MaMh>
        <TenMh>Mạng căn bản	</TenMh>
        <SoGio>30</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMh>THDC</MaMh>
        <TenMh>Tin học đại cương</TenMh>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMh>THVP</MaMh>
        <TenMh>Tin học văn phòng</TenMh>
        <SoGio>45</SoGio>
    </MonHoc>
    <MonHoc>
        <MaMh>XLA</MaMh>
        <TenMh>Xử lý ảnh</TenMh>
        <SoGio>45</SoGio>
    </MonHoc>
</ListMonHoc>
