=== PhDxunq/JSON/Lesson1/Bai5/student_report.dtd
<!ELEMENT STUDENT_REPORT (STUDENT_INFO,GRADES)>

<!ELEMENT STUDENT_INFO (FULL_NAME, CLASS, GENDER, DATE_OF_BIRTH)>
<!ELEMENT FULL_NAME (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT GENDER (#PCDATA)>
<!ELEMENT DATE_OF_BIRTH (#PCDATA)>

<!ELEMENT GRADES (SUBJECT+)>

<!ELEMENT SUBJECT (NAME ,SEM_1, SEM_2, AVG_SCORE)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT SEM_1 (#PCDATA)>
<!ELEMENT SEM_2 (#PCDATA)>
<!ELEMENT AVG_SCORE (#PCDATA)>

=== PhDxunq/JSON/Lesson1/Bai5/student_report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE STUDENT_REPORT SYSTEM "student_report.dtd">

<STUDENT_REPORT>
    <STUDENT_INFO>
        <FULL_NAME>Pham Huu Dung</FULL_NAME>
        <CLASS>C2309L</CLASS>
        <GENDER>MALE</GENDER>
        <DATE_OF_BIRTH>07/07/2004</DATE_OF_BIRTH>
    </STUDENT_INFO>
    <GRADES>
        <SUBJECT>
            <NAME>C PROGRAMMING</NAME>
            <SEM_1>8</SEM_1>
            <SEM_2>10</SEM_2>
            <AVG_SCORE>9</AVG_SCORE>
        </SUBJECT>
        <SUBJECT>
            <NAME>PHP</NAME>
            <SEM_1>8</SEM_1>
            <SEM_2>8</SEM_2>
            <AVG_SCORE>8</AVG_SCORE>
        </SUBJECT>
    </GRADES>
</STUDENT_REPORT>
