=== PhDxunq/JSON/Day1/Bai3/mydtd.dtd
<!ELEMENT DOCUMENT (CUSTOMER)>
<!ELEMENT CUSTOMER (NAME,DATE,ORDERS)>
<!ATTLIST CUSTOMER TYPE CDATA "Good">

<!ELEMENT NAME (LAST_NAME,FIRST_NAME)>
<!ELEMENT LAST_NAME (#PCDATA)>
<!ELEMENT FIRST_NAME (#PCDATA)>

<!ELEMENT DATE (#PCDATA)>

<!ELEMENT ORDERS (ITEM+)>
<!ATTLIST ORDERS class CDATA "SanPham">

<!ELEMENT ITEM (PRODUCT,NUMBER,PRICE)>
<!ELEMENT PRODUCT (#PCDATA|PRODUCT_ID)*>
<!ELEMENT PRODUCT_ID (#PCDATA)>
<!ELEMENT NUMBER (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>

=== PhDxunq/JSON/Lesson1/Bai3/bai_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "mydtd.dtd">
<DOCUMENT>
    <CUSTOMER TYPE = "Good">
        <NAME>
            <LAST_NAME> aaa </LAST_NAME>
            <FIRST_NAME> bbb </FIRST_NAME>
        </NAME>
        <DATE> 1/1/03 </DATE>
        <ORDERS class="SanPham">
            <ITEM>
                <PRODUCT>
                    <PRODUCT_ID>12</PRODUCT_ID>
                </PRODUCT>
                <NUMBER>25</NUMBER>
                <PRICE>20</PRICE>
            </ITEM>
            <ITEM>
                <PRODUCT>Tomatoes</PRODUCT>
                <NUMBER>25</NUMBER>
                <PRICE>3</PRICE>
            </ITEM>
        </ORDERS>
    </CUSTOMER>
</DOCUMENT>
