=== PhDxunq/JSON/Lesson2/Bai3/order_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://hocvietcode.com"
xmlns="https://hocvietcode.com" 
elementFormDefault="qualified"
>
    <xs:element name="OrderList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ProductList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Quantity" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Street" type="xs:string"/>
                            <xs:element name="City" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PhDxunq/JSON/Lesson2/Bai3/order_list.xml
<?xml version="1.0" encoding="UTF-8"?>


<OrderList

xmlns="https://hocvietcode.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://hocvietcode.com order_list.xsd"
>
    <ProductList>
        <Product>
            <Name>Product A</Name>
            <Quantity>2</Quantity>
        </Product>
        <Product>
            <Name>Product B</Name>
            <Quantity>1</Quantity>
        </Product>
    </ProductList>
    <Address>
        <Street>Cau Giay</Street>
        <City>Ha Noi</City>
    </Address>
</OrderList>
