=== PhDxunq/JSON/Lesson2/Bai2/product_list.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://hocvietcode.com"
xmlns="https://hocvietcode.com" 
elementFormDefault="qualified"
>
    <xs:element name="ProductList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Price" type="xs:float"/>
                            <xs:element name="Description" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="type" >
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="simple"/>
                                    <xs:enumeration value="variable"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PhDxunq/JSON/Lesson2/Bai2/product_list.xml
<?xml version="1.0" encoding="UTF-8"?>

<ProductList 
xmlns="https://hocvietcode.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://hocvietcode.com product_list.xsd"
>
    <Product type="simple">
        <Name>Product A</Name>
        <Price>20</Price>
        <Description>Basic</Description>
    </Product>
    <Product type="variable">
        <Name>Product B</Name>
        <Price>50</Price>
        <Description>Red</Description>
    </Product>
</ProductList>
