=== PhDxunq/JSON/Lesson3/Bai4/KetQua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListKetQua">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="KetQua" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSv" type="xs:string"/>
                            <xs:element name="MaMh" type="xs:string"/>
                            <xs:element name="DiemThi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:float"> 
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PhDxunq/JSON/Lesson3/Bai4/KetQua.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="KetQua.xsl" type="text/xsl"?>

<ListKetQua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="KetQua.xsd">
    <KetQua>
        <MaSv>sv01</MaSv>
        <MaMh>THDC</MaMh>
        <DiemThi>8</DiemThi>
    </KetQua>
    <KetQua>
        <MaSv>sv01</MaSv>
        <MaMh>THVP</MaMh>
        <DiemThi>9.5</DiemThi>
    </KetQua>
    <KetQua>
        <MaSv>sv02</MaSv>
        <MaMh>THDC</MaMh>
        <DiemThi>5.5</DiemThi>
    </KetQua>
    <KetQua>
        <MaSv>sv02</MaSv>
        <MaMh>THVP</MaMh>
        <DiemThi>10</DiemThi>
    </KetQua>
    <KetQua>
        <MaSv>sv03</MaSv>
        <MaMh>THDC</MaMh>
        <DiemThi>9</DiemThi>
    </KetQua>
    <KetQua>
        <MaSv>sv03</MaSv>
        <MaMh>THVP</MaMh>
        <DiemThi>4.5</DiemThi>
    </KetQua>
</ListKetQua>
